#!/bin/sh

if ! ls "$HOME"/.config/shadowreplay;then
    cp example_config "$HOME"/.config/shadowreplay
fi

DIR=$(dirname "$0")

# Install dependencies on Arch
if [ -e "/etc/arch-release" ]; then
    echo "Installing dependencies"
    sudo pacman --noconfirm -S ffmpeg libnotify
fi

# move shadowreplay to /usr/local/bin
sudo install "$DIR/shadowreplay" /usr/local/bin 

# Save the xbindkeys config
# if xbindkeys is installed
if ls /bin/xbindkeys;then
    echo """
    # make F9 save ShadowRePlay replay
    "killall --user "$USER" --ignore-case --signal SIGTERM ffmpeg"
       F9
    
    # make F10 kill ShadowRePlay
    "killall -s1 ffmpeg"
       F10
    """ >> "$HOME/.xbindkeysrc"
fi

# Install systemd user service
mkdir -p "$HOME/.config/systemd/user/"
cp "$DIR/shadowreplay.service" "$HOME/.config/systemd/user/"
# Start shadowreplay service
systemctl --user enable --now shadowreplay
systemctl --user restart --now shadowreplay

echo """

Installation is complete!
Press F9 to save a replay"""
