#!/bin/sh

DIR=$(dirname "$0")

# Install dependencies on Arch
if [ -e "/etc/arch-release" ]; then
    echo "Installing dependencies"
    sudo pacman --noconfirm -S xbindkeys ffmpeg libnotify
fi

# move shadowplay to /usr/bin
sudo install "$DIR/shadowplay" /usr/local/bin 

# Save the xbindkeys config
echo """
# make F9 save Shadowplay replay
"killall --user $USER --ignore-case --signal SIGTERM ffmpeg"
   F9

# make F10 kill Shadowplay
"killall -s1 ffmpeg"
   F10
""" >> "$HOME/.xbindkeysrc"

# Install systemd user service
mkdir -p "$HOME/.config/systemd/user/"
cp "$DIR/shadowplay.service" "$HOME/.config/systemd/user/"
cp "$DIR/shadowplay.timer" "$HOME/.config/systemd/user/"
# Start shadowplay service
systemctl --user enable --now shadowplay
systemctl --user restart --now shadowplay

echo """


Installation is complete!
Press F9 to save a replay"""