#!/bin/sh

set -eu

RESOLUTION="$(xdpyinfo | grep dimensions | awk 'NR==1{print $2}')"
SOFTWARE_ENCODE=true
FPS="60" 
ENCODER_STANDARD=h264
REPLAY_BUFFER="00:05:00"
VIDEO_FOLDER="$HOME/Videos/"

# Source user-specific config
. $HOME/.config/shadowplay

if [ -e "$VIDEO_FOLDER" ]; then
    echo "Video directory already exists."
else
    mkdir "$VIDEO_FOLDER"
fi

if lspci | awk '/VGA.*ATI/' >/dev/null;then
    ENCODER_API=vaapi
elif lspci | awk '/VGA.*NVIDIA/' >/dev/null;then
    ENCODER_API=nvenc
elif lspci | awk '/VGA.*Intel/' >/dev/null;then
    ENCODER_API=qsv
fi

ENCODER="$ENCODER_STANDARD"_"$ENCODER_API"

if $SOFTWARE_ENCODE;then
    ENCODER_API=
    ENCODER=libx264
fi

BASEDIR=$(dirname "$0")

DATE=$(date +%Y-%d-%m-%H:%M:%S)
FILE="$VIDEO_FOLDER/replay-$DATE.mp4"

case $ENCODER_API in
    "vaapi")
        ffmpeg_command(){
            ffmpeg \
                -threads 0 \
                -thread_queue_size 32768 \
                -f x11grab \
                -s "$RESOLUTION" \
                -r ${FPS} \
                -i "$DISPLAY" \
                -f pulse -i default \
                -ar 44100 \
                -c:v "$ENCODER" -vf format='nv12|vaapi,hwupload' -vaapi_device /dev/dri/renderD128 \
                -y \
                /tmp/shadowplay.mp4
            };;
    "nvenc")    
        ffmpeg_command(){
            ffmpeg \
                -f pulse -i default \
                -f x11grab \
                -framerate ${FPS} \
                -s "$RESOLUTION" \
                -i "$DISPLAY" \
                -c:v "$ENCODER" \
                -preset:v llhq \
                -profile:v high \
                -pix_fmt nv12 \
                -b:v 15M \
                -acodec aac \
                -y \
                /tmp/shadowplay.mp4
            };;
    "qsv")      
        ffmpeg_command(){
            ffmpeg \
                -threads 0 \
                -thread_queue_size 32768 \
                -f x11grab \
                -s "$RESOLUTION" \
                -r ${FPS} \
                -i "$DISPLAY" \
                -f pulse -i default \
                -ar 44100 \
                -c:v "$ENCODER" \
                -y \
                /tmp/shadowplay.mp4
            };;
    *)
        ffmpeg_command(){
            ffmpeg \
                -threads 0 \
                -thread_queue_size 32768 \
                -f x11grab \
                -s "$RESOLUTION" \
                -r ${FPS} \
                -i "$DISPLAY" \
                -f pulse -i default \
                -ar 44100 \
                -c:v "$ENCODER" -preset medium \
                -y \
                /tmp/shadowplay.mp4
            };;
esac

ffmpeg_command ||

ffmpeg \
    -sseof -$REPLAY_BUFFER \
    -i /tmp/shadowplay.mp4 \
    -vcodec copy -acodec copy \
    "$FILE" -loglevel quiet &&

rm /tmp/shadowplay.mp4 &&

notify-send -i video \
	"Shadowplay" \
	"Replay saved to $FILE"

cd "$BASEDIR" &&
    
./shadowplay
