#!/bin/sh

set -eu

RESOLUTION="$(xdpyinfo | grep dimensions | awk 'NR==1{print $2}')"
SOFTWARE_ENCODE=false
FPS="60" 
ENCODER_STANDARD=h264
REPLAY_BUFFER="00:05:00"

if ls "$HOME"/Videos;then
    VIDEO_FOLDER="$HOME"/Videos
elif ls /usr/bin/xdg-user-dir;then
    VIDEO_FOLDER="$(xdg-user-dir VIDEOS)" 
else
    mkdir "$HOME"/Videos
    VIDEO_FOLDER="$HOME"/Videos
fi

# Source user-specific config
. $HOME/.config/shadowreplay

if $NONFREE_AMD_ENCODER;then
    ENCODER_API=amf
elif lspci | grep 'VGA.*ATI' >/dev/null;then
    ENCODER_API=vaapi
elif lspci | grep 'VGA.*NVIDIA' >/dev/null;then
    ENCODER_API=nvenc
elif lspci | grep 'VGA.*Intel' >/dev/null;then
    ENCODER_API=qsv
fi

ENCODER="$ENCODER_STANDARD"_"$ENCODER_API"

if $SOFTWARE_ENCODE;then
    ENCODER_API=
    ENCODER=libx264
fi

BASEDIR=$(dirname "$0")

DATE=$(date +%Y-%d-%m-%H:%M:%S)
FILE="$VIDEO_FOLDER/replay-$DATE.mp4"

case $ENCODER_API in
    "vaapi")
        ffmpeg_command(){
            ffmpeg \
                -threads 0 \
                -thread_queue_size 32768 \
                -f x11grab \
                -s "$RESOLUTION" \
                -r ${FPS} \
                -i "$DISPLAY" \
                -f pulse -i default \
                -ar 44100 \
                -c:v "$ENCODER" -vf format='nv12|vaapi,hwupload' -vaapi_device /dev/dri/renderD128 \
                -y \
                /tmp/shadowreplay.mp4
            };;
    "amf")
        ffmpeg_command(){
            ffmpeg \
                -threads 0 \
                -thread_queue_size 32768 \
                -f x11grab \
                -s "$RESOLUTION" \
                -r ${FPS} \
                -i "$DISPLAY" \
                -f pulse -i default \
                -ar 44100 \
                -c:v "$ENCODER" \
                -y \
                /tmp/shadowreplay.mp4
            };;
    "nvenc")    
        ffmpeg_command(){
            ffmpeg \
                -f pulse -i default \
                -f x11grab \
                -framerate ${FPS} \
                -s "$RESOLUTION" \
                -i "$DISPLAY" \
                -c:v "$ENCODER" \
                -preset:v llhq \
                -profile:v high \
                -pix_fmt nv12 \
                -b:v 15M \
                -acodec aac \
                -y \
                /tmp/shadowreplay.mp4
            };;
    "qsv")      
        ffmpeg_command(){
            ffmpeg \
                -threads 0 \
                -thread_queue_size 32768 \
                -f x11grab \
                -s "$RESOLUTION" \
                -r ${FPS} \
                -i "$DISPLAY" \
                -f pulse -i default \
                -ar 44100 \
                -c:v "$ENCODER" \
                -y \
                /tmp/shadowreplay.mp4
            };;
    *)
        ffmpeg_command(){
            ffmpeg \
                -threads 0 \
                -thread_queue_size 32768 \
                -f x11grab \
                -s "$RESOLUTION" \
                -r ${FPS} \
                -i "$DISPLAY" \
                -f pulse -i default \
                -ar 44100 \
                -c:v "$ENCODER" -preset medium \
                -y \
                /tmp/shadowreplay.mp4
            };;
esac

ffmpeg_command ||

ffmpeg \
    -sseof -$REPLAY_BUFFER \
    -i /tmp/shadowreplay.mp4 \
    -vcodec copy -acodec copy \
    "$FILE" -loglevel quiet &&

rm /tmp/shadowreplay.mp4 &&

notify-send -i video \
	"ShadowRePlay" \
	"Replay saved to $FILE"

cd "$BASEDIR" &&
    
./shadowreplay
